exec-once = swaync
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = awww-daemon && awww img ~/data/.config/Pictures/wallpaper1.png
exec-once = blueman-applet
