exec-once = swaync
exec-once = waybar
exec-once = awww-daemon && awww img ~/data/.config/Pictures/wallpaper1.png
exec-once = blueman-applet
exec-once = nm-applet
exec-once= wl-paste --type text --watch cliphist store
exec-once= wl-paste --type image --watch cliphist store
