general {
    lock_cmd = pidof hyprlock
    on_lock_cmd = notify-send "you are idle" "starting hyprlock" && nmcli networking off && playerctl pause
    on_unlock_cmd = notify-send "welcome back" "you may continue your work" && nmcli networking off && playerctl play
}
