general {
    hide_cursor = false
    ignore_empty_input = true
    immediate_render = true
    text_trim = true
    fractional_scaling = 1
    screencopy_mode = 0
    fail_timeout = 100
}
auth {
    pam:enabled = true
    pam:module = hyprlock
    fingerprint:enabled = false
}
animations {
    enabled = true
}
